spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tagnote
    username: developer
    password: developer
  view:
    prefix: /WEB-INF/views/
    suffix: .jsp
server:
  port: 8080